### ISSUE TITLE
Missing Weapon

### ISSUE THREAD

**Issue by kbdbull** [asdfjackal/warframe-checklist#10]
Hello, I first wanted to say Thank You guys so much for making the Warframe Checklist! it has Helped me immensely with tracking down weapons! . secondly, I wanted to point out sadly, that I believe there is a weapon missing in the Melee section i noticed that the Endura is missing, i did a control + F to see if it was anywhere and it is not.. 

Mastery level 7
Tenno Lab Researched

Again Thank you guys so much for making this Checklist

**Comment by asdfjackal** [comment]
I'm so sorry for this taking so long. Between wrapping up my summer work and starting classes back up I have been swamped and your issue slipped through my radar. The change has been made now.

Thank you for your kind words and contribution to this project. People like you help keep this site updated even when I am not actively following warframe updates.
