### ISSUE TITLE
New items

### ISSUE THREAD

**Issue by Tithen-Firion** [asdfjackal/warframe-checklist#13]
**Warframe:**
[Gara](http://warframe.wikia.com/wiki/Gara)

**Primary:**
[Argonak](http://warframe.wikia.com/wiki/Argonak)
[Astilla](http://warframe.wikia.com/wiki/Astilla)

**Secondary:**
[Fusilai](http://warframe.wikia.com/wiki/Fusilai)
[Prisma Angstrum](http://warframe.wikia.com/wiki/Prisma_Angstrum)

**Melee:**
[Dual Krohkur](http://warframe.wikia.com/wiki/Dual_Krohkur)
Furax Wraith is obtainable now from Cetus Bounty missions.
[Jat Kusar](http://warframe.wikia.com/wiki/Jat_Kusar)
[Krohkur](http://warframe.wikia.com/wiki/Krohkur)
[Volnus](http://warframe.wikia.com/wiki/Volnus)
[Zaw](http://warframe.wikia.com/wiki/Zaw)

**Arch-Gun:**
Imperator Vandal is obtainable from Fomorian Sabotage missions.

**Comment by asdfjackal** [comment]
Items added to master branch but not deployed. Will update my game and pull the new version number for updating the master empty list and tool header later today.

**Comment by asdfjackal** [comment]
Issue implemented and pushed to gh-pages branch.
