### ISSUE TITLE
Wrong data

### ISSUE THREAD

**Issue by RylaiSlyfe** [asdfjackal/warframe-checklist#14]
* Prisma Gorgon is misspelled as Prisma Gorgan.
* The Machete is not unobtainable. You can get it through daily rewards.
* Gorgon Wraith is obtained by defeating the reocurring Razorback Armada event.

**Comment by asdfjackal** [comment]
I have verified that your requested changes are accurate to the latest version of the game. I will get these changes implemented sometime in the following week.

Could you provide a screenshot of your login screen as described [here](https://github.com/asdfjackal/warframe-checklist#background) under the header "Important." It is not required but would help speed up the process.

**Comment by RylaiSlyfe** [comment]
![2017-11-01 01_20_17-warframe](https://user-images.githubusercontent.com/16038306/32254756-507755e2-bea3-11e7-8e37-d57241ebd2da.png)

**Comment by asdfjackal** [comment]
Adding a new change to this issue, Arca Titron is not an Energy Lab weapon. Blueprint can be bought from the market.

**Comment by asdfjackal** [comment]
Updates have been applied, live version has been updated to reflect updates.
