### ISSUE TITLE
Plague Star event added new weapons

### ISSUE THREAD

**Issue by RylaiSlyfe** [asdfjackal/warframe-checklist#16]
new weapons are Zaw(Plague Keewar) and Zaw(Plague Kripath)

also Aklex Prime is vaulted or sometimes obtainable from Baro Ki'Teer
and Hikou Prime are vaulted too

![Login Screen 11.17.2017](https://user-images.githubusercontent.com/16038306/32958650-633680d0-cbbf-11e7-8e29-470186d25302.png)

**Comment by asdfjackal** [comment]
I have confirmed the reported changes.

Progress Tracker:
- [ ] Add [Plague Keewar](http://warframe.wikia.com/wiki/Plague_Keewar)
- [ ] Add [Plague Kripath](http://warframe.wikia.com/wiki/Plague_Kripath)
- [ ] [Aklex Prime](http://warframe.wikia.com/wiki/Aklex_Prime) -> Vaulted, Baro
- [ ] [Hikou Prime](http://warframe.wikia.com/wiki/Hikou_Prime) -> Vaulted
