### ISSUE TITLE
Update 22.4.0: Baza and Cassowar

### ISSUE THREAD

**Issue by RylaiSlyfe** [asdfjackal/warframe-checklist#17]
New update brought new Weapons. 

- [Baza](http://warframe.wikia.com/wiki/Baza) (Primary, Tenno Lab)

- [Cassowar](http://warframe.wikia.com/wiki/Cassowar) (Melee, Tenno Lab)

![Update 22.4.0](https://user-images.githubusercontent.com/16038306/33189354-295624d2-d0a2-11e7-9c4c-17a677a4cae5.png)

**Comment by asdfjackal** [comment]
Changes have been made and deployed to live.
