### ISSUE TITLE
Missing Weapons (Amps)

### ISSUE THREAD

**Issue by RylaiSlyfe** [asdfjackal/warframe-checklist#18]
With the Plains of Eidolon update also came the Amps which are completely missing here. They only provide Mastery Rank after "guilding", and like the Zaws only the one component (and the starter weapon) provide rank.
to add are:
- Amp(Mote)
- Amp(Raplak)
- Amp(Shwaak)
- Amp(Granmu)
all are aquired from Quill Onkko.

I also got you into [Warframehub](https://warframehub.github.io/). Found under Information->Mastery.

![2017-12-01](https://user-images.githubusercontent.com/16038306/33476767-76d9fd50-d683-11e7-8bea-5181873579f7.png)

**Comment by asdfjackal** [comment]
Added. Sorry this one took so long, between finals and travel I didn't have time to commit to adding this.
Additionally, implemented a system to handle the creation of new categories like the Amps, which was a major hurdle in making this change.
