### ISSUE TITLE
Update 22.8.0 + Hotfix 22.8.0.1

### ISSUE THREAD

**Issue by RylaiSlyfe** [asdfjackal/warframe-checklist#20]
New Weapons:

- [Corinth](http://warframe.wikia.com/wiki/Corinth), Primary, MR: 10, no research required, Aquisition: Market
- [Gunsen](http://warframe.wikia.com/wiki/Gunsen), Melee, MR: 10, Research required!, Aquisition: Tenno Lab
- [Quartakk](http://warframe.wikia.com/wiki/Quartakk), Primary, MR: 9, no research required, Aquisition: Ghoul Purge Event
- [Stubba](http://warframe.wikia.com/wiki/Stubba), Secondary, MR: 5, no research required, Aquisition: Ghoul Purge Event

![2017-12-22](https://user-images.githubusercontent.com/16038306/34292948-0e0c6d90-e703-11e7-97d4-ff32e40a123d.png)

**Comment by asdfjackal** [comment]
Closed and deployed alongside #18 and #19
