### ISSUE TITLE
Content Change

### ISSUE THREAD

**Issue by RylaiSlyfe** [asdfjackal/warframe-checklist#23]
They changed a lot of Mastery Rank requirements with the weapon changes.
First Changes came in the [Update 22.12.0](https://forums.warframe.com/topic/918482-shrine-of-the-eidolon-update-22120/) February 9th, 2018. Later followed some changes in [Hotfix 22.13.3](https://forums.warframe.com/topic/924885-shrine-of-the-eidolon-hotfix-22133/) February 21st, 2018.

This is some time ago but up to today those are the only changes and once Implemented everything should be up to date. Current version is 22.15.0

Primaries:

Weapon | New Mastery Rank
------------ | -------------
Amprex | 10
Astilla | 10
Attica | 7
Boar Prime | 12
Boltor Prime | 13
Braton Prime | 8
Braton Vandal | 4
Burston Prime | 12
Buzlok | 11
Cernos | 6
Cernos Prime | 12
Convectrix | 7
Daikyu | 10
Dera Vandal | 7
Dex Sybaris | 7
Drakgoon | 5
Dread | 5
Ferrox | 14
Glaxion | 8
Gorgon Wraith | 7
Grakata | 5
Grinlok | 7
Ignis | 5
Ignis Wraith | 9
Javlok | 7
Karak | 1
Karak Wraith | 7
Khom | 5
Lanka | 10
Latron Prime | 10
Latron Wraith | 7
Mutalist Cernos | 7
Opticor | 14
Paracyst | 7
Paris | 3
Paris Prime | 8
Phage | 11
Prisma Gorgon | 10
Prisma Grakata | 11
Quartakk | 10
Rubico | 6
Snipetron Vandal | 5
Sobek | 7
Soma Prime | 7
Strun Wraith | 10
Supra | 12
Supra Vandal | 14
Synapse | 11
Tiberon | 10
Tigris | 9
Vectis | 2
Vectis Prime | 14
Vulkar | 3
Vulkar Wraith | 7
Zenith | 10
Zhuge | 10

Secondaries:

Weapon | New Mastery Rank
------------- | --------------
Akbronco Prime | 10
Akjagara | 8
Aklato | 3
Aklex Prime | 13
Akmagnus | 12
Aksomati | 9
Akstiletto | 8
Akstiletto Prime | 10
Akvasto | 8
Akzani | 4
Atomos | 5
Azima | 6
Ballistica Prime | 14
Bronco Prime | 4
Cycron | 8
Despair | 4
Dex Furis | 10
Dual Cestra | 7
Dual Toxocyst | 11
Embolist | 9
Fusilai | 7
Kohmak | 5
Kulstar | 5
Lato Prime | 14
Lato Vandal | 7
Lex Prime | 8
Magnus | 10
Marelok | 7
Pox | 9
Prisma Angstrum | 8
Sancti Castanas | 10
Secura Dual Cestra | 10
Sicarus Prime | 14
Spira | 8
Spira Prime | 10
Stubba | 7
Synoid Gammacor | 7
Talons | 8
Telos Akbolto | 11
Twin Grakatas | 9
Twin Gremlins | 5
Twin Kohmaks | 10
Twin Rogga | 9
Twin Vipers | 5
Twin Vipers Wraith | 7
Tysis | 9
Vasto | 4
Vasto Prime | 10
Vaykor Marelok | 10
Viper | 4
Zakti | 10

Took me so long to post this because I wanted to actually get into this and try to implement it myself but yeah...didn't have the time yet so here it is for you to do, sorry :D
![2018-03-08-warframe](https://user-images.githubusercontent.com/16038306/37149868-7f3f9a96-22c7-11e8-8689-6c4168bd9a61.png)

**Comment by asdfjackal** [comment]
Merged in #24 and made additional commit 7b962f6 to change the empty_list.js object (should not result in any changes to users) as well as the app header to reflect the current version.
