### ISSUE TITLE
Beasts of the Sanctuary: Update 22.18.0

### ISSUE THREAD

**Issue by RylaiSlyfe** [asdfjackal/warframe-checklist#26]
Heya, I can't do this on my own this time. here's the data though. (Found in [Update 22.18.0](https://forums.warframe.com/topic/947321-beasts-of-the-sanctuary-update-22180/)

Add:

 Warframe
- { title: "Khora", acquisition: "Sanctuary Onslaught(Game Mode)", mr: 0 },

Primary
- { title: "Veldt", acquisition: "Tenno Lab", mr: 8 },

Secondary
- { title: "Hystrix", acquisition: "Market", mr: 7 },

Melee
- { title: "Dual Keres", acquisition: "Market", mr: 7 },

Zaws
- { title: "Zaw (Sepfahn)", acquisition: "Hok's Anvil"},
- { title: "Zaw (Rabvee)", acquisition: "Hok's Anvil"},
- { title: "Zaw (Dokrahm)", acquisition: "Hok's Anvil"},

Change:
Primary
- { title: "Supra Vandal", acquisition: "Baro Ki'Teer", mr: 14 },

Secondary
- { title: "Lato Vandal", acquisition: "Sanctuary Onslaught(Game Mode)", mr: 7 },
- { title: "Braton Vandal", acquisition: "Sanctuary Onslaught(Game Mode)", mr: 4 },

![2018-04-23 11_31_25-warframe](https://user-images.githubusercontent.com/16038306/39118513-e0c9c9f8-46e9-11e8-9755-e8404ce81619.png)

**Comment by asdfjackal** [comment]
Sorry for the delay, I will try to get this added and deployed tonight.
