### ISSUE TITLE
[enhancement] 2 acquisition columns for warframes?

### ISSUE THREAD

**Issue by pgbconfirmit** [asdfjackal/warframe-checklist#28]
Just a suggestion... The acquisition column for warframes doesn't seem to make it clear if the details listed are for the frame BP or for the component BPs. In some cases, it seems to refer to the frame BP, while in others, it refers to the component BPs.
It might be helpful to have 2 different acquisition columns, one for the frame and one for the components.

**Comment by asdfjackal** [comment]
Deployed the changes. Let me know if there are any issues with the new system. If there are any items outside of the frames category that need updates create a new issue with the changes needed and I will apply them when I get a chance.
