### ISSUE TITLE
Misc data errors

### ISSUE THREAD

**Issue by fwyrl** [asdfjackal/warframe-checklist#3]
Missing:
Prisma Obex (Baro Item, melee)
Supra Vandal (Event Item - Ambulas Reborn, primary)

Wrong Obtainment Data:
Quanta Vandal: Listed as Unobtainable, Is actually a Baro Item

Wrong Name:
Wraith Twin Vipers (Listed as Twin Vipers Wraith in-game)

**Comment by asdfjackal** [comment]
Thank you for submitting these changes.

I have committed the changes and deployed the updates to be live. If there are any issues with the changes feel free to re-open this issue or make a new one.
