### ISSUE TITLE
Missing Excalibur Umbra

### ISSUE THREAD

**Issue by t-pearce** [asdfjackal/warframe-checklist#31]

**Comment by t-pearce** [comment]
And the Skiajati, and the vaulted status of the most recent stuff.

**Comment by asdfjackal** [comment]
Would you be able to list the vaulted status changes that need to be made in this issue? If so I can get them entered much faster.

**Comment by TomeWyrm** [comment]
Vaulted:
Nekros Prime
Tigris Prime
Galatine Prime

Added:
Chroma Prime
Rubico Prime
Gram Prime

**Comment by TomeWyrm** [comment]
Also the Revenant frame, and Phantasma shotgun

**Comment by RylaiSlyfe** [comment]
so to summarize, there are some things missing. Yes, a lot of stuff is missing and not up to date. To make this all easier I'll List down all things that will need to be changed for it to be up to date in the next hours.
Stay tuned for an easy overview :D

**Comment by RylaiSlyfe** [comment]
Latest Version: Update 23.10 (Called just Chimera)

### To add:
**Warframe:**
{ title: "Chroma Prime", acquisition: "Relic", mr: 6 },
{ title: "Excalibur Umbra", acquisition: "The Sacrifice (Quest)", mr: 0 },
{ title: "Limbo Prime", acquisition: "Relic", mr: 4 },
{ title: "Revenant", acquisition: "Mask of the Revenant (Quest)", mr: 0 },

**Primary:**
{ title: "Rubico Prime", acquisition: "Relic", mr: 12 },
{ title: "Phantasma", acquisition: "Market", mr: 9 },

**Secondary:**
{ title: "Zylok", acquisition: "The Pyrus Project Event", mr: 6 },
{ title: "Pyrana Prime", acquisition: "Relic", mr: 13 },

**Melee:**
{ title: "Destreza Prime", acquisition: "Relic", mr: 10 },
{ title: "Gram Prime", acquisition: "Relic", mr: 14 },
{ title: "Paracesis", acquisition: "Chimera Prologue (Quest)", mr: 10 },
{ title: "Pupacyst", acquisition: "Bio Lab", lab: "Bio Lab", mr: 7 },
{ title: "Falcor", acquisition: "Energy Lab", lab: "Energy Lab", mr: 8 },
{ title: "Skiajati", acquisition: "The Sacrifice (Quest)", mr: 11 },

**Amp:**
{ title: "Rahn", acquisition: "Quill Onkko"},



### new Vaults:

**Warframe:**
{ title: "Nekros Prime", acquisition: "Vaulted", vaulted: true, mr: 0 },
{ title: "Valkyr Prime", acquisition: "Vaulted", vaulted: true, mr: 0 },

**Primary:**
{ title: "Tigris Prime", acquisition: "Vaulted", vaulted: true, mr: 13 },
{ title: "Cernos Prime", acquisition: "Vaulted", vaulted: true, mr: 12 },

**Melee:**
{ title: "Galatine Prime", acquisition: "Vaulted", vaulted: true, mr: 13 },
{ title: "Venka Prime", acquisition: "Vaulted", vaulted: true, mr: 8 },

![2018-10-15 22_26_53-warframe](https://user-images.githubusercontent.com/16038306/46976330-741f1c80-d0c9-11e8-9317-d072bf2d25d7.png)
