### ISSUE TITLE
Fortuna Update

### ISSUE THREAD

**Issue by asdfjackal** [asdfjackal/warframe-checklist#33]
List of new items to be added, will need to wait for community to update wiki with requirements:

Garuda - Frame
Nagantaka - ?
Kreska - ? 
Ocucor - ?
Battacor - ?
Oxylus - Companion

Kitgun - Secondary
Kitgun Variants (By Chamber?)
- Catchmoon
- Gaze
- Rattleguts
- Tombfinger

Moas - Companions
- Para
- Lambeo
- Oloro

K-Drives (Probably will not be added unless they can be leveled)

**Comment by Jakub-Michalak** [comment]
I added frame and weapons. Didn't add kitgun and Moas, because I'm not sure how these work just yet.

**Comment by asdfjackal** [comment]
Merged in changes by @Jakub-Michalak 
Will handle kitguns/moas/kdrives before pushing to live server.

**Comment by asdfjackal** [comment]
Changes handled in 86099ee, will update version number and deploy later tonight.
