### ISSUE TITLE
Miter in wrong s[p

### ISSUE THREAD

**Issue by BrownZFilmZ** [asdfjackal/warframe-checklist#6]
MK-1 Weapons go after Miter

**Comment by asdfjackal** [comment]
I'm currently sorting things alphabetically and, in the eyes of javascript, a capital K comes before a lowercase k, so MZ would come before Ma. As far as I am concerned, this is working as intended.

**Comment by BrownZFilmZ** [comment]
Why not just use a custom sort, that compares the toLower form (all lower-case) of the string?
